### ISSUE TITLE
Example1 does not compile

### ISSUE THREAD

**Issue by drozzy** [Palmik/snaplet-mongodb-minimalistic#5]
Doing `cabal install` gives the following error:

> $ cabal install
> Resolving dependencies...
> cabal.exe: Could not resolve dependencies:
> trying: snaplet-mongodb-minimalistic-example1-0.0.1 (user goal)
> trying: mongoDB-1.3.0/installed-137... (dependency of
> snaplet-mongodb-minimalistic-example1-0.0.1)
> trying: transformers-base-0.4.1/installed-9d4... (dependency of
> mongoDB-1.3.0/installed-137...)
> next goal: snap-server (dependency of
> snaplet-mongodb-minimalistic-example1-0.0.1)
> rejecting: snap-server-0.9.0/installed-5b0..., 0.9.0, 0.8.1.1, 0.8.1, 0.8.0.1,
> 0.8.0 (conflict: snaplet-mongodb-minimalistic-example1 => snap-server==0.7._)
> rejecting: snap-server-0.7.0.1 (conflict: transformers-base =>
> transformers==0.3.0.0/installed-e82..., snap-server => transformers>=0.2 &&
> <0.3)
> rejecting: snap-server-0.7 (conflict: mongoDB =>
> array==0.4.0.0/installed-3cf..., snap-server => array>=0.2 && <0.4)
> rejecting: snap-server-0.6.0.1, 0.6.0, 0.5.5, 0.5.4, 0.5.3.1, 0.5.3, 0.5.2,
> 0.5.1.4, 0.5.1.3, 0.5.1.2, 0.5.1.1, 0.5.1, 0.5.0, 0.4.3, 0.4.2, 0.4.1,
> 0.4.0.2, 0.4.0.1, 0.4.0, 0.3.1.1, 0.3.1, 0.3.0, 0.2.16.2, 0.2.16.1, 0.2.16,
> 0.2.15.1, 0.2.15, 0.2.14.1, 0.2.14, 0.2.13.3, 0.2.13.2, 0.2.13.1, 0.2.13,
> 0.2.12, 0.2.11, 0.2.10.2, 0.2.10.1, 0.2.10, 0.2.9, 0.2.8.1, 0.2.8, 0.2.7.2,
> 0.2.7.1, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.2, 0.2.1, 0.1.4, 0.1.3, 0.1.2, 0.1.1
> (conflict: snaplet-mongodb-minimalistic-example1 => snap-server==0.7._)

**Comment by Palmik** [comment]
Hi, the example was not updated for for newer versions of snap, I will look into it later, but maybe simply changing the snap dependency in the cabal file will do the trick.

**Comment by drozzy** [comment]
Ya, I'm not an expert in cabal, and this error looks cryptic to me :-)
