### ISSUE TITLE
Where does the database come from?

### ISSUE THREAD

**Issue by drozzy** [Palmik/snaplet-mongodb-minimalistic#6]
In the example1 Site.hs:
https://github.com/Palmik/snaplet-mongodb-minimalistic/blob/master/examples/example1/src/Site.hs

on the line:

```
d <- nestSnaplet "database" database $ mongoDBInit 10 (host "127.0.0.1") "Snaplet-MongoDB"
```

where does the `database` keyword come from? Any chance of using explicit imports? Much appreciated...

**Comment by Palmik** [comment]
Hi, it comes from the module `Application`, it's a lens generated by the `makeLens ''App`. I will make the imports qualified with the transition (of the example) to snap 0.9.
